### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by MLKhub** [clarivate/wosstarter_python_client#1]
Thank you very much for posting this project. It is really helpful to retrieve data from WOS starter API.

While I tried to get authentication and found two issues:

1, the API link is not correct. The correct one should be:
https://api.clarivate.com/apis/wos-starter/v1

2, need to modify the "clarivate/wos_starter/client/api_client.py" for the following lines:
def update_params_for_auth(self, headers, auth_settings, resource_path, method, body):
    - if not auth_settings: # remove line 1237
    - return                         # remove line 1238
    + auth_setting_keys = self.configuration.auth_settings().keys()  #add

    for auth in auth_setting_keys:
...........................................................................................................................................

Would you please let me know if I misunderstood anything? If the above lines work for you, would you please update your version? I would like to share your library out with my colleagues. 

Thanks again for your wonderful project.

**Comment by gneissone** [comment]
The authentication issue should be fixed. Please note you must add your API key into your environment like `export API_KEY="your_actual_starter_api_token"` to use the example code as written. Let me know if you continue to have issues.
