### ISSUE TITLE
Example code will not run

### ISSUE THREAD

**Issue by ericleasemorgan** [clarivate/wosstarter_python_client#2]
The example code on this repository's home page will not run. There are all sorts of syntax errors, indention problems, etc. I believe I ought to be able to copy the code, paste it into my editor, save the file as something like practice.py, and then run it with something like "python ./practice.py" Can you make this happen?  :)  --Eric Morgan

**Comment by gneissone** [comment]
The example code should be fixed. Please note you must add your API key into your environment like `export API_KEY="your_actual_starter_api_token"` to use the example code as written.

**Comment by ericleasemorgan** [comment]
Thank you for the prompt update.

After creating a virtual environment, gitting, installing the libraries, and running the sample code things run. But now I am waiting (impatiently) for my various wos-* keys to be approved. Once I get valid key I will be able to see if the sample code works for me. FYI

Also, please confirm. Previously, when I used APILite, I had zero keys in my environment, and things seemed to work. APILite seems to no longer work. Adding a key to my environment is new feature/necessity in StarterAPI?

**Comment by gneissone** [comment]
The SOAP versions of our APIs were [sunset](https://support.clarivate.com/ScientificandAcademicResearch/s/article/Web-of-Science-SOAP-API-Sunset-Frequently-asked-questions-FAQs?language=en_US) in November of last year. The REST version of the Lite API is still available. 

All WoS APIs require authentication, however the SOAP API required a separate initial call to the auth endpoint to begin a session. The REST APIs don't require this, however you must include your API key with every request. The example code provided reads the key from your environment, but you could also provide it directly to the client.
`configuration.api_key['ClarivateApiKeyAuth'] = "YOUR_STARTER_API_KEY"`

Re:approvals, most requests are processed within 24 hours. I see your Starter request has already been approved on our end, we're just awaiting configuration. I also see a pending request for the Researcher API, however that API requires a separate subscription (unlike Starter which is included with a WoS subscription). If you're still interested, please contact your account manager for pricing.
