### ISSUE TITLE
Number of citations is empty

### ISSUE THREAD

**Issue by YuryPakhomov** [clarivate/wosstarter_python_client#7]
Any queries for articles give empty "citations" field.
.... citations=[], .....
How to get its value?

Thank you in advance

**Comment by gneissone** [comment]
You must be a Web of Science subscriber and have an 'institutional' Starter API token to see citation values. If you're a subscriber and not seeing citation counts it may be an entitlements configuration error, let me know if that's the case.

**Comment by YuryPakhomov** [comment]
Ok. I have Free Plan API KEY only.
